Traceback (most recent call last):
  File "/home/jovyan/jonglae/Retry1/2. B-BOX/base_yolo_detection.py", line 16, in <module>
    model.train(data=train_data, epochs=50, imgsz=640, batch=16, lr0=0.001, device='cuda', amp=False, patience=20)
  File "/home/jovyan/.conda/envs/aipbase/lib/python3.10/site-packages/ultralytics/engine/model.py", line 802, in train
    self.trainer.train()
  File "/home/jovyan/.conda/envs/aipbase/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 207, in train
    self._do_train(world_size)
  File "/home/jovyan/.conda/envs/aipbase/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 437, in _do_train
    self.metrics, self.fitness = self.validate()
  File "/home/jovyan/.conda/envs/aipbase/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 602, in validate
    metrics = self.validator(self)
  File "/home/jovyan/.conda/envs/aipbase/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/jovyan/.conda/envs/aipbase/lib/python3.10/site-packages/ultralytics/engine/validator.py", line 196, in __call__
    stats = self.get_stats()
  File "/home/jovyan/.conda/envs/aipbase/lib/python3.10/site-packages/ultralytics/models/yolo/detect/val.py", line 181, in get_stats
    stats = {k: torch.cat(v, 0).cpu().numpy() for k, v in self.stats.items()}  # to numpy
  File "/home/jovyan/.conda/envs/aipbase/lib/python3.10/site-packages/ultralytics/models/yolo/detect/val.py", line 181, in <dictcomp>
    stats = {k: torch.cat(v, 0).cpu().numpy() for k, v in self.stats.items()}  # to numpy
RuntimeError: torch.cat(): expected a non-empty list of Tensors
