Traceback (most recent call last):
  File "/home/jovyan/jonglae/Retry1/DO/1_1_SAM_base_train.py", line 159, in <module>
    train_sam()
  File "/home/jovyan/jonglae/Retry1/DO/1_1_SAM_base_train.py", line 74, in train_sam
    loss = compute_bce_loss(segmented_image, target_mask)
  File "/home/jovyan/jonglae/Retry1/DO/1_1_SAM_base_train.py", line 149, in compute_bce_loss
    return F.binary_cross_entropy(torch.sigmoid(predicted_mask), target_mask)
  File "/home/jovyan/.conda/envs/aipbase/lib/python3.10/site-packages/torch/nn/functional.py", line 3545, in binary_cross_entropy
    raise ValueError(
ValueError: Using a target size (torch.Size([1, 3, 2948])) that is different to the input size (torch.Size([3, 2948, 2948])) is deprecated. Please ensure they have the same size.
