Traceback (most recent call last):
  File "/home/jovyan/jonglae/Retry1/DO/3_MobileNet_OCR_Train.py", line 68, in <module>
    train_dataset = MNISTDataset(TRAIN_IMAGES_PATH, TRAIN_LABELS_PATH, transform=transform)
  File "/home/jovyan/jonglae/Retry1/DO/3_MobileNet_OCR_Train.py", line 27, in __init__
    self.images = self._load_images(images_path)
  File "/home/jovyan/jonglae/Retry1/DO/3_MobileNet_OCR_Train.py", line 33, in _load_images
    _ = int.from_bytes(f.read(4), byteorder='big')  # magic number
  File "/home/jovyan/.conda/envs/aipbase2/lib/python3.10/gzip.py", line 301, in read
    return self._buffer.read(size)
  File "/home/jovyan/.conda/envs/aipbase2/lib/python3.10/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/jovyan/.conda/envs/aipbase2/lib/python3.10/gzip.py", line 488, in read
    if not self._read_gzip_header():
  File "/home/jovyan/.conda/envs/aipbase2/lib/python3.10/gzip.py", line 436, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'\x00\x00')
