/home/jovyan/SAM_Model/segment_anything/build_sam.py:105: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(f)
Epoch 1/10
Traceback (most recent call last):
  File "/home/jovyan/jonglae/Retry1/DO/1_1_SAM_base_train.py", line 112, in <module>
    train_sam()
  File "/home/jovyan/jonglae/Retry1/DO/1_1_SAM_base_train.py", line 45, in train_sam
    segmented_image, measurements_dict = perform_segmentation_and_measurement(mask_generator, image, bboxes, measurements)
  File "/home/jovyan/jonglae/Retry1/DO/1_1_SAM_base_train.py", line 86, in perform_segmentation_and_measurement
    masks = mask_generator.generate(image)  # 이미지에 대해 자동으로 마스크 생성
  File "/home/jovyan/.conda/envs/aipbase/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/jovyan/SAM_Model/segment_anything/automatic_mask_generator.py", line 163, in generate
    mask_data = self._generate_masks(image)
  File "/home/jovyan/SAM_Model/segment_anything/automatic_mask_generator.py", line 198, in _generate_masks
    orig_size = image.shape[:2]
  File "/home/jovyan/.conda/envs/aipbase/lib/python3.10/site-packages/PIL/Image.py", line 548, in __getattr__
    raise AttributeError(name)
AttributeError: shape. Did you mean: 'save'?
