Traceback (most recent call last):
  File "/home/jovyan/jonglae/Retry1/Segmentation/1.SAM_NoDataAug2.py", line 149, in <module>
    train_and_test_sam(sam_model, train_loader, test_loader, num_epochs=num_epochs, save_folder=save_folder, test_save_folder=test_save_folder)
  File "/home/jovyan/jonglae/Retry1/Segmentation/1.SAM_NoDataAug2.py", line 80, in train_and_test_sam
    outputs = model(images, multimask_output)  # multimask_output 인자 추가
  File "/home/jovyan/.conda/envs/aipbase/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jovyan/.conda/envs/aipbase/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/.conda/envs/aipbase/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/jovyan/SAM_Model/segment_anything/modeling/sam.py", line 97, in forward
    input_images = torch.stack([self.preprocess(x["image"]) for x in batched_input], dim=0)
  File "/home/jovyan/SAM_Model/segment_anything/modeling/sam.py", line 97, in <listcomp>
    input_images = torch.stack([self.preprocess(x["image"]) for x in batched_input], dim=0)
IndexError: too many indices for tensor of dimension 3
